# Generated by Django 4.1.7 on 2024-02-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=10)),
                ('phone1', models.CharField(max_length=10)),
                ('email1', models.CharField(max_length=10)),
                ('txt', models.CharField(max_length=10)),
                ('message1', models.CharField(max_length=100)),
            ],
        ),
    ]
