# Generated by Django 4.1.7 on 2024-02-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactuser',
            name='email1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='contactuser',
            name='name1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='contactuser',
            name='txt',
            field=models.CharField(max_length=50),
        ),
    ]
