# Generated by Django 4.1.7 on 2024-02-05 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeedbackForm',
            new_name='FeedbackUser',
        ),
    ]
