# Generated by Django 4.1.7 on 2024-02-06 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_rename_feedbackform_feedbackuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeedbackUser',
            new_name='Feedback',
        ),
    ]
